# Generated by Django 4.0.2 on 2022-03-10 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('age_rating', models.CharField(max_length=3)),
                ('duration', models.CharField(max_length=3)),
                ('trailer_desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cost', models.FloatField()),
                ('is_settled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uweflix.account')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('email', models.EmailField(max_length=254)),
                ('is_validated', models.BooleanField(default=0)),
            ],
            bases=('uweflix.account',),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=3)),
                ('date_time', models.DateTimeField()),
                ('film', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='uweflix.film')),
                ('transaction', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='uweflix.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ClubRep',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uweflix.customer')),
                ('club_rep_num', models.CharField(max_length=50)),
            ],
            bases=('uweflix.customer',),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='uweflix.customer'),
        ),
    ]
