# Generated by Django 4.0.2 on 2022-03-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit',
            field=models.FloatField(default=0.0),
        ),
    ]
