# Generated by Django 4.0.2 on 2022-05-02 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubrep',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uweflix.club'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='apply_covid_restrictions',
            field=models.BooleanField(null=True),
        ),
    ]
