# Generated by Django 4.0.2 on 2022-02-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('employee_type', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('age_rating', models.CharField(max_length=3)),
                ('duration', models.CharField(max_length=3)),
                ('trailer_desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='ClubRep',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
