# Generated by Django 4.0.3 on 2022-04-07 18:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0002_delete_clubrep'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_rep_num', models.CharField(max_length=8)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob1', models.DateField(default=datetime.date.today, verbose_name='dob')),
                ('club', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uweflix.club')),
            ],
        ),
    ]
