# Generated by Django 4.0.3 on 2022-04-07 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0003_clubrep'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACCOUNT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('card_num', models.CharField(max_length=8)),
                ('expiry_date', models.CharField(max_length=8)),
                ('discount_rate', models.IntegerField(default=0)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uweflix.club')),
            ],
        ),
    ]
