# Generated by Django 4.0.2 on 2022-04-03 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0003_alter_clubrep_club_rep_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubrep',
            name='club_rep_num',
            field=models.CharField(max_length=8, validators=[django.core.validators.MinValueValidator(8)]),
        ),
    ]
