# Generated by Django 4.0.2 on 2022-02-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0003_customer_clubrep'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Account',
        ),
    ]
