# Generated by Django 4.0.2 on 2022-03-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0005_rename_employee_type_account_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='trailer_desc',
            new_name='description',
        ),
    ]
