# Generated by Django 4.0.2 on 2022-03-22 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0005_alter_club_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrep',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uweflix.club'),
        ),
        migrations.AddField(
            model_name='showing',
            name='screen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uweflix.screen'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='showing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='uweflix.showing'),
        ),
        migrations.AlterField(
            model_name='clubrep',
            name='club_rep_num',
            field=models.CharField(max_length=8),
        ),
    ]
