# Generated by Django 4.0.2 on 2022-03-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0006_clubrep_club_showing_screen_ticket_showing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='remaining_tickets',
            field=models.IntegerField(default=150),
        ),
    ]
