# Generated by Django 4.0.3 on 2022-05-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0006_alter_film_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='request_to_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to=''),
        ),
    ]
