# Generated by Django 4.0.2 on 2022-03-08 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uweflix', '0007_rename_description_film_trailer_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='uweflix.account'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cost', models.FloatField()),
                ('is_settled', models.BooleanField()),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='uweflix.account')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=3)),
                ('date_time', models.DateTimeField()),
                ('film', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='uweflix.film')),
                ('transaction', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='uweflix.transaction')),
            ],
        ),
    ]
